import os
import re
import json
import base64
import hashlib
import html
import secrets
import smtplib
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from collections import defaultdict, deque

from dotenv import load_dotenv
from authlib.integrations.starlette_client import OAuth
from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, UploadFile, status
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from psycopg import Error as DatabaseError, IntegrityError, connect
from psycopg.rows import dict_row
from starlette.middleware.sessions import SessionMiddleware
from supabase import create_client

# --- Configuración Inicial ---
BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env")

MAX_FILE_SIZE = 5 * 1024 * 1024
ALLOWED_EXTENSIONS = {".pdf", ".doc", ".docx"}
CV_BUCKET = "curriculums"
EMAIL_PATTERN = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
ECUADOR_MOBILE_PATTERN = re.compile(r"(?:\+593|593|0)9\d{8}$")
REQUEST_LIMIT = 5
REQUEST_WINDOW_SECONDS = 3600
attempts = defaultdict(deque)
security = HTTPBasic()
oauth = OAuth()

SESSION_SECRET = os.getenv("SESSION_SECRET")
if not SESSION_SECRET or len(SESSION_SECRET) < 32:
    raise RuntimeError("SESSION_SECRET debe tener al menos 32 caracteres.")

# --- Configuración OAuth ---
oauth.register(
    name="google",
    client_id=os.getenv("GOOGLE_CLIENT_ID"),
    client_secret=os.getenv("GOOGLE_CLIENT_SECRET"),
    server_metadata_url="https://accounts.google.com/.well-known/openid-configuration",
    client_kwargs={"scope": "openid email profile"},
)
oauth.register(
    name="apple",
    client_id=os.getenv("APPLE_CLIENT_ID"),
    client_secret=os.getenv("APPLE_CLIENT_SECRET"),
    authorize_url="https://appleid.apple.com/auth/authorize",
    access_token_url="https://appleid.apple.com/auth/token",
    jwks_uri="https://appleid.apple.com/auth/keys",
    client_kwargs={"scope": "name email"},
)

# --- Funciones de Base de Datos y Storage ---
def get_db():
    connection_string = os.getenv("DATABASE_URL")
    if not connection_string:
        raise RuntimeError("Falta DATABASE_URL en las variables de entorno.")
    return connect(connection_string, connect_timeout=10, row_factory=dict_row)

def get_storage():
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        raise RuntimeError("Configura SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY.")
    return create_client(url, key).storage.from_(CV_BUCKET)

def init_db():
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS usuarios (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                proveedor TEXT NOT NULL,
                proveedor_id TEXT NOT NULL,
                nombre TEXT NOT NULL,
                email TEXT,
                fecha_creacion TIMESTAMP NOT NULL,
                ultimo_acceso TIMESTAMP NOT NULL,
                UNIQUE (proveedor, proveedor_id)
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS cuentas_educativas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario_id BIGINT NOT NULL UNIQUE,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                fecha_registro TIMESTAMP NOT NULL DEFAULT NOW()
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS postulantes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombres TEXT NOT NULL, apellidos TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
                telefono TEXT NOT NULL, ciudad TEXT NOT NULL, cargo_postula TEXT NOT NULL,
                experiencia TEXT NOT NULL, nivel_educacion TEXT NOT NULL,
                disponibilidad TEXT NOT NULL, mensaje TEXT NOT NULL, hoja_vida TEXT,
                fecha_registro TIMESTAMP NOT NULL, usuario_id BIGINT
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS preguntas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                texto TEXT NOT NULL, tipo TEXT NOT NULL, opciones TEXT,
                obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW()
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS respuestas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                postulante_id BIGINT NOT NULL, usuario_id BIGINT,
                pregunta_id BIGINT NOT NULL, respuesta TEXT NOT NULL,
                fecha_respuesta TIMESTAMP NOT NULL DEFAULT NOW()
            )
        """)
        conn.commit()

def guardar_usuario(proveedor: str, proveedor_id: str, nombre: str, email: str | None):
    fecha = datetime.now(timezone.utc).replace(tzinfo=None)
    with get_db() as conn:
        cursor = conn.cursor()
        row = cursor.execute(
            "SELECT id FROM usuarios WHERE proveedor = %s AND proveedor_id = %s",
            (proveedor, proveedor_id),
        ).fetchone()
        if row:
            usuario_id = row["id"]
            cursor.execute(
                "UPDATE usuarios SET nombre = %s, email = %s, ultimo_acceso = %s WHERE id = %s",
                (nombre, email, fecha, usuario_id),
            )
        else:
            usuario_id = cursor.execute("""
                INSERT INTO usuarios (proveedor, proveedor_id, nombre, email, fecha_creacion, ultimo_acceso)
                VALUES (%s, %s, %s, %s, %s, %s) RETURNING id
                """,
                (proveedor, proveedor_id, nombre, email, fecha, fecha),
            ).fetchone()["id"]
        conn.commit()
    return usuario_id

# --- MODO EDUCATIVO - CONTRASEÑAS ---
def hash_password(password: str):
    return f"PLAIN_TEXT:{password}"

def password_valido(password: str, almacenado: str):
    if almacenado.startswith("PLAIN_TEXT:"):
        return password == almacenado.replace("PLAIN_TEXT:", "")
    try:
        salt_b64, hash_b64 = almacenado.split("$", 1)
        digest = hashlib.scrypt(password.encode("utf-8"), salt=base64.b64decode(salt_b64), n=16384, r=8, p=1)
        return secrets.compare_digest(base64.b64encode(digest).decode(), hash_b64)
    except (ValueError, TypeError):
        return False

def normalizar_celular(telefono: str):
    celular = re.sub(r"[\s().-]", "", telefono.strip())
    if not ECUADOR_MOBILE_PATTERN.fullmatch(celular):
        raise HTTPException(status_code=400, detail="Ingresa un celular ecuatoriano válido (ej.: +593 99 123 4567).")
    return celular

def enviar_aviso(postulante: dict, archivo: bytes | None, nombre_archivo: str | None):
    usuario = os.getenv("GMAIL_USER")
    clave = os.getenv("GMAIL_APP_PASSWORD")
    destino = os.getenv("CORREO_DESTINO")
    if not all((usuario, clave, destino)):
        return
    mensaje = EmailMessage()
    mensaje["From"] = usuario
    mensaje["To"] = destino
    mensaje["Subject"] = f"Nueva postulación: {postulante['nombres']} {postulante['apellidos']}"
    mensaje.set_content(
        f"Nombre: {postulante['nombres']} {postulante['apellidos']}\n"
        f"Correo: {postulante['email']}\nTeléfono: {postulante['telefono']}\n"
        f"Ciudad: {postulante['ciudad']}\nCargo: {postulante['cargo_postula']}\n"
        f"Experiencia: {postulante['experiencia']}\nEducación: {postulante['nivel_educacion']}\n"
        f"Disponibilidad: {postulante['disponibilidad']}\n\nMensaje:\n{postulante['mensaje']}"
    )
    if archivo and nombre_archivo:
        mensaje.add_attachment(archivo, maintype="application", subtype="octet-stream", filename=nombre_archivo)
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as servidor:
            servidor.login(usuario, clave)
            servidor.send_message(mensaje)
    except (OSError, smtplib.SMTPException):
        return

# --- Inicialización de la App ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    crear_cuenta_examen()
    yield

# Declaramos la app AQUÍ para que esté disponible globalmente
app = FastAPI(title="Portal de empleo", lifespan=lifespan)
app.add_middleware(
    SessionMiddleware,
    secret_key=SESSION_SECRET,
    https_only=os.getenv("COOKIE_SECURE", "false").lower() == "true",
    same_site="lax",
    max_age=8 * 60 * 60,
)
app.mount("/static", StaticFiles(directory=BASE_DIR / "static"), name="static")

@app.middleware("http")
async def agregar_cabeceras_seguridad(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    return response

@app.exception_handler(DatabaseError)
async def database_error(_: Request, __: DatabaseError):
    return JSONResponse(status_code=503, content={"detail": "La base de datos no está disponible. Intenta nuevamente en unos minutos."})

# --- Helpers ---
def check_request_limit(request: Request):
    client_ip = request.client.host if request.client else "unknown"
    now = datetime.now(timezone.utc).timestamp()
    history = attempts[client_ip]
    while history and now - history[0] > REQUEST_WINDOW_SECONDS:
        history.popleft()
    if len(history) >= REQUEST_LIMIT:
        raise HTTPException(status_code=429, detail="Has alcanzado el máximo de postulaciones permitido. Intenta más tarde.")
    history.append(now)

def validar_cv(archivo: UploadFile, contenido: bytes):
    extension = Path(archivo.filename or "").suffix.lower()
    if extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail="El CV debe ser PDF, DOC o DOCX.")
    if len(contenido) > MAX_FILE_SIZE:
        raise HTTPException(status_code=400, detail="El CV no puede superar 5 MB.")
    if extension == ".pdf" and not contenido.startswith(b"%PDF-"):
        raise HTTPException(status_code=400, detail="El archivo PDF no es válido.")
    if extension == ".docx" and not contenido.startswith(b"PK"):
        raise HTTPException(status_code=400, detail="El archivo DOCX no es válido.")

def usuario_requerido(request: Request):
    usuario = request.session.get("usuario")
    if not usuario:
        raise HTTPException(status_code=401, detail="Inicia sesión para continuar.")
    return usuario

def proveedor_configurado(proveedor: str):
    if proveedor == "google":
        return bool(os.getenv("GOOGLE_CLIENT_ID") and os.getenv("GOOGLE_CLIENT_SECRET"))
    if proveedor == "apple":
        return bool(os.getenv("APPLE_CLIENT_ID") and os.getenv("APPLE_CLIENT_SECRET"))
    return False

class NuevaPregunta(BaseModel):
    texto: str = Field(min_length=3, max_length=300)
    tipo: str
    opciones: list[str] = []
    obligatorio: bool = True

def obtener_preguntas_activas():
    with get_db() as conn:
        cursor = conn.cursor()
        rows = cursor.execute(
            "SELECT id, texto, tipo, opciones, obligatorio FROM preguntas WHERE activo = TRUE ORDER BY id"
        ).fetchall()
    preguntas = []
    for row in rows:
        opciones = json.loads(row["opciones"]) if row["opciones"] else []
        preguntas.append({"id": row["id"], "texto": row["texto"], "tipo": row["tipo"], "opciones": opciones, "obligatorio": bool(row["obligatorio"])})
    return preguntas

def admin_required(credentials: HTTPBasicCredentials = Depends(security)):
    expected_user = os.getenv("ADMIN_USER")
    expected_password = os.getenv("ADMIN_PASSWORD")
    if not expected_user or not expected_password:
        raise RuntimeError("Configura ADMIN_USER y ADMIN_PASSWORD en .env.")
    valid_user = secrets.compare_digest(credentials.username, expected_user)
    valid_password = secrets.compare_digest(credentials.password, expected_password)
    if not (valid_user and valid_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Credenciales inválidas.",
            headers={"WWW-Authenticate": "Basic"},
        )
    return credentials.username

def crear_cuenta_examen():
    email = os.getenv("EXAM_DEMO_EMAIL", "").strip().lower()
    password = os.getenv("EXAM_DEMO_PASSWORD", "")
    if not email or not password:
        return
    with get_db() as conn:
        existente = conn.cursor().execute(
            "SELECT id FROM cuentas_educativas WHERE email = %s", (email,)
        ).fetchone()
    if existente:
        return
    usuario_id = guardar_usuario("educativo", email, "Usuario ficticio de examen", email)
    try:
        with get_db() as conn:
            conn.cursor().execute(
                "INSERT INTO cuentas_educativas (usuario_id, email, password_hash) VALUES (%s, %s, %s)",
                (usuario_id, email, hash_password(password)),
            )
            conn.commit()
    except IntegrityError:
        return

# --- Rutas del Portal ---
@app.get("/", response_class=HTMLResponse)
def inicio(request: Request):
    if request.session.get("usuario"):
        return RedirectResponse("/postulacion", status_code=status.HTTP_303_SEE_OTHER)
    return (BASE_DIR / "templates" / "login.html").read_text(encoding="utf-8")

@app.get("/postulacion", response_class=HTMLResponse)
def postulacion(_: dict = Depends(usuario_requerido)):
    return (BASE_DIR / "templates" / "index.html").read_text(encoding="utf-8")

@app.get("/acceso/educativo", response_class=HTMLResponse)
def acceso_educativo():
    return (BASE_DIR / "templates" / "acceso_educativo.html").read_text(encoding="utf-8")

@app.post("/acceso/educativo")
def iniciar_cuenta_educativa(request: Request, email: str = Form(...), password: str = Form(...)):
    correo = email.strip().lower()
    if not EMAIL_PATTERN.fullmatch(correo):
        raise HTTPException(status_code=400, detail="Ingresa un correo válido.")
    with get_db() as conn:
        row = conn.cursor().execute("""
            SELECT ce.usuario_id, ce.password_hash, u.nombre
            FROM cuentas_educativas ce INNER JOIN usuarios u ON u.id = ce.usuario_id
            WHERE ce.email = %s
            """, (correo,)
        ).fetchone()
    if not row or not password_valido(password, row["password_hash"]):
        raise HTTPException(status_code=401, detail="Correo o contraseña incorrectos.")
    request.session["usuario"] = {"id": row["usuario_id"], "nombre": row["nombre"], "proveedor": "educativo"}
    return {"ok": True, "redirect": "/postulacion"}

@app.post("/registro/educativo")
def registrar_cuenta_educativa(nombre: str = Form(...), email: str = Form(...), password: str = Form(...)):
    correo = email.strip().lower()
    if not EMAIL_PATTERN.fullmatch(correo):
        raise HTTPException(status_code=400, detail="Ingresa un correo válido.")
    if len(nombre.strip()) < 2 or len(nombre.strip()) > 150:
        raise HTTPException(status_code=400, detail="Ingresa tu nombre completo.")
    try:
        usuario_id = guardar_usuario("educativo", correo, nombre.strip(), correo)
        with get_db() as conn:
            conn.cursor().execute(
                "INSERT INTO cuentas_educativas (usuario_id, email, password_hash) VALUES (%s, %s, %s)",
                (usuario_id, correo, hash_password(password)),
            )
            conn.commit()
    except IntegrityError:
        raise HTTPException(status_code=409, detail="Ya existe una cuenta con ese correo.")
    return {"ok": True, "mensaje": "Cuenta creada. Ya puedes iniciar sesión."}

@app.post("/acceso/demostracion")
def acceso_demostracion(request: Request):
    usuario_id = guardar_usuario("demostracion", "usuario-demo", "Usuario de demostración", "demo@portal-educativo.local")
    request.session["usuario"] = {"id": usuario_id, "nombre": "Usuario de demostración", "proveedor": "demostracion"}
    return RedirectResponse("/postulacion", status_code=status.HTTP_303_SEE_OTHER)

@app.get("/ingresar/{proveedor}")
async def ingresar(proveedor: str, request: Request):
    if proveedor not in {"google", "apple"}:
        raise HTTPException(status_code=404, detail="Proveedor no disponible.")
    if not proveedor_configurado(proveedor):
        return HTMLResponse((BASE_DIR / "templates" / f"sim_{proveedor}.html").read_text(encoding="utf-8"))
    cliente = oauth.create_client(proveedor)
    callback = request.url_for(f"autorizar_{proveedor}")
    if proveedor == "apple":
        return await cliente.authorize_redirect(request, callback, response_mode="form_post")
    return await cliente.authorize_redirect(request, callback)

@app.post("/sim/ingresar/{proveedor}")
async def sim_ingresar(proveedor: str, request: Request, email: str = Form(...), nombre: str = Form(...)):
    if proveedor not in {"google", "apple"}:
        raise HTTPException(status_code=404, detail="Proveedor no disponible.")
    correo = email.strip().lower()
    if not EMAIL_PATTERN.fullmatch(correo):
        raise HTTPException(status_code=400, detail="Ingresa un correo válido.")
    if len(nombre.strip()) < 2:
        raise HTTPException(status_code=400, detail="Ingresa un nombre válido.")
    usuario_id = guardar_usuario(proveedor, correo, nombre.strip() or correo, correo)
    request.session["usuario"] = {"id": usuario_id, "nombre": nombre.strip() or correo, "proveedor": proveedor}
    return RedirectResponse("/postulacion", status_code=status.HTTP_303_SEE_OTHER)

@app.get("/autorizacion/google")
async def autorizar_google(request: Request):
    token = await oauth.google.authorize_access_token(request)
    datos = token.get("userinfo") or await oauth.google.userinfo(token=token)
    if not datos.get("email") or not datos.get("sub"):
        raise HTTPException(status_code=400, detail="Google no proporcionó un correo electrónico.")
    nombre = datos.get("name", "Postulante")
    usuario_id = guardar_usuario("google", datos["sub"], nombre, datos["email"])
    request.session["usuario"] = {"id": usuario_id, "nombre": nombre, "proveedor": "google"}
    return RedirectResponse("/postulacion", status_code=status.HTTP_303_SEE_OTHER)

@app.api_route("/autorizacion/apple", methods=["GET", "POST"])
async def autorizar_apple(request: Request):
    token = await oauth.apple.authorize_access_token(request)
    datos = await oauth.apple.parse_id_token(request, token)
    if not datos.get("sub"):
        raise HTTPException(status_code=400, detail="Apple no proporcionó una identidad válida.")
    nombre = datos.get("name", "Postulante")
    usuario_id = guardar_usuario("apple", datos["sub"], nombre, datos.get("email"))
    request.session["usuario"] = {"id": usuario_id, "nombre": nombre, "proveedor": "apple"}
    return RedirectResponse("/postulacion", status_code=status.HTTP_303_SEE_OTHER)

@app.post("/cerrar-sesion")
def cerrar_sesion(request: Request):
    request.session.clear()
    return RedirectResponse("/", status_code=status.HTTP_303_SEE_OTHER)

@app.post("/postular")
async def postular(
    request: Request,
    usuario: dict = Depends(usuario_requerido),
    nombres: str = Form(..., min_length=2, max_length=80),
    apellidos: str = Form(..., min_length=2, max_length=80),
    email: str = Form(..., max_length=120),
    telefono: str = Form(..., min_length=7, max_length=30),
    ciudad: str = Form(..., min_length=2, max_length=80),
    area: str = Form(..., min_length=2, max_length=80),
    cargo_postula: str = Form(..., min_length=2, max_length=100),
    experiencia: str = Form(..., max_length=50),
    nivel_educacion: str = Form(..., max_length=80),
    disponibilidad: str = Form(..., max_length=60),
    mensaje: str = Form(..., min_length=10, max_length=1500),
    respuestas_json: str = Form("[]", max_length=10_000),
    acepta_privacidad: bool = Form(...),
    hoja_vida: UploadFile = File(...),
):
    content_length = request.headers.get("content-length")
    if content_length and content_length.isdigit() and int(content_length) > MAX_FILE_SIZE + 100_000:
        raise HTTPException(status_code=413, detail="La solicitud supera el tamaño permitido.")
    check_request_limit(request)
    if not acepta_privacidad:
        raise HTTPException(status_code=400, detail="Debes aceptar el tratamiento de tus datos.")
    if not EMAIL_PATTERN.fullmatch(email.strip()):
        raise HTTPException(status_code=400, detail="Ingresa un correo electrónico válido.")
    celular = normalizar_celular(telefono)
    if not all((nombres.strip(), apellidos.strip(), ciudad.strip(), area.strip(), cargo_postula.strip(), experiencia.strip(), nivel_educacion.strip(), disponibilidad.strip(), mensaje.strip())):
        raise HTTPException(status_code=400, detail="Completa todos los campos obligatorios.")
    try:
        respuestas_enviadas = json.loads(respuestas_json)
        if not isinstance(respuestas_enviadas, list):
            raise ValueError
    except (json.JSONDecodeError, ValueError):
        raise HTTPException(status_code=400, detail="Las respuestas adicionales no son válidas.")
    
    preguntas = obtener_preguntas_activas()
    respuestas_por_id = {str(item.get("pregunta_id")): str(item.get("respuesta", "")).strip() for item in respuestas_enviadas if isinstance(item, dict)}
    respuestas_validas = []
    for pregunta in preguntas:
        respuesta = respuestas_por_id.get(str(pregunta["id"]), "")
        if pregunta["obligatorio"] and not respuesta:
            raise HTTPException(status_code=400, detail=f"Responde: {pregunta['texto']}")
        if respuesta:
            if len(respuesta) > 1500:
                raise HTTPException(status_code=400, detail="Una respuesta adicional supera el límite permitido.")
            if pregunta["tipo"] == "opcion_multiple" and respuesta not in pregunta["opciones"]:
                raise HTTPException(status_code=400, detail="Selecciona una opción válida.")
            respuestas_validas.append((pregunta["id"], respuesta))
    
    ruta_cv = None
    if not hoja_vida.filename:
        raise HTTPException(status_code=400, detail="Adjunta tu hoja de vida.")
    extension = Path(hoja_vida.filename).suffix.lower()
    contenido = await hoja_vida.read(MAX_FILE_SIZE + 1)
    validar_cv(hoja_vida, contenido)
    nombre_archivo = f"{uuid.uuid4().hex}{extension}"
    ruta_cv = nombre_archivo
    try:
        get_storage().upload(
            ruta_cv,
            contenido,
            {"content-type": hoja_vida.content_type or "application/octet-stream", "upsert": "false"},
        )
    except Exception as error:
        raise HTTPException(status_code=503, detail="No fue posible guardar la hoja de vida.") from error

    fecha = datetime.now(timezone.utc).replace(tzinfo=None)
    try:
        with get_db() as conn:
            cursor = conn.cursor()
            postulante_id = cursor.execute("""
                INSERT INTO postulantes (
                    nombres, apellidos, email, telefono, ciudad, cargo_postula,
                    experiencia, nivel_educacion, disponibilidad, mensaje,
                    hoja_vida, fecha_registro, usuario_id
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id
                """,
                (nombres.strip(), apellidos.strip(), email.strip().lower(), celular, ciudad.strip(),
                 cargo_postula.strip(), experiencia, nivel_educacion.strip(), disponibilidad,
                 mensaje.strip(), ruta_cv, fecha, usuario["id"]),
            ).fetchone()["id"]
            for pregunta_id, respuesta in respuestas_validas:
                cursor.execute(
                    "INSERT INTO respuestas (postulante_id, usuario_id, pregunta_id, respuesta) VALUES (%s, %s, %s, %s)",
                    (postulante_id, usuario["id"], pregunta_id, respuesta),
                )
            conn.commit()
    except IntegrityError:
        get_storage().remove([ruta_cv])
        raise HTTPException(status_code=409, detail="Ya hay una postulación con ese correo.")
    except DatabaseError:
        get_storage().remove([ruta_cv])
        raise
    enviar_aviso(
        {"nombres": nombres, "apellidos": apellidos, "email": email, "telefono": telefono,
         "ciudad": ciudad, "cargo_postula": cargo_postula, "experiencia": experiencia,
         "nivel_educacion": nivel_educacion, "disponibilidad": disponibilidad, "mensaje": mensaje},
        contenido,
        ruta_cv,
    )
    return {"ok": True, "mensaje": "Tu postulación fue enviada correctamente."}

@app.get("/admin", response_class=HTMLResponse)
def admin(_: str = Depends(admin_required)):
    return (BASE_DIR / "templates" / "admin.html").read_text(encoding="utf-8")

@app.get("/admin/credenciales-demo", response_class=HTMLResponse)
def credenciales_demo(_: str = Depends(admin_required)):
    email = os.getenv("EXAM_DEMO_EMAIL", "").strip()
    password = os.getenv("EXAM_DEMO_PASSWORD", "")
    if not email or not password:
        raise HTTPException(status_code=404, detail="Configura EXAM_DEMO_EMAIL y EXAM_DEMO_PASSWORD para la demostración.")
    return HTMLResponse(
        "<main style='font-family:Arial,sans-serif;max-width:620px;margin:56px auto;padding:28px'>"
        "<h1>Credenciales de demostración</h1>"
        "<p>Esta es una cuenta ficticia exclusiva para la evaluación. Las contraseñas de usuarios reales nunca se muestran.</p>"
        f"<p><strong>Correo:</strong> {html.escape(email)}</p>"
        f"<p><strong>Contraseña de prueba:</strong> {html.escape(password)}</p>"
        "<p><a href='/admin'>← Volver a administración</a></p></main>"
    )

@app.get("/api/postulantes")
def listar_postulantes(_: str = Depends(admin_required)):
    with get_db() as conn:
        rows = conn.cursor().execute("SELECT * FROM postulantes ORDER BY id DESC").fetchall()
    return rows

@app.get("/api/preguntas")
def listar_preguntas_publicas(_: dict = Depends(usuario_requerido)):
    return obtener_preguntas_activas()

@app.get("/api/admin/preguntas")
def listar_preguntas_admin(_: str = Depends(admin_required)):
    with get_db() as conn:
        rows = conn.cursor().execute("SELECT id, texto, tipo, opciones, obligatorio, activo FROM preguntas ORDER BY id DESC").fetchall()
    return [{"id": row["id"], "texto": row["texto"], "tipo": row["tipo"], "opciones": json.loads(row["opciones"]) if row["opciones"] else [], "obligatorio": bool(row["obligatorio"]), "activo": bool(row["activo"])} for row in rows]

@app.post("/api/admin/preguntas")
def crear_pregunta(pregunta: NuevaPregunta, _: str = Depends(admin_required)):
    if pregunta.tipo not in {"texto", "textarea", "opcion_multiple"}:
        raise HTTPException(status_code=400, detail="Tipo de pregunta no válido.")
    opciones = [opcion.strip() for opcion in pregunta.opciones if opcion.strip()]
    if pregunta.tipo == "opcion_multiple" and len(opciones) < 2:
        raise HTTPException(status_code=400, detail="Incluye al menos dos opciones.")
    with get_db() as conn:
        conn.cursor().execute(
            "INSERT INTO preguntas (texto, tipo, opciones, obligatorio) VALUES (%s, %s, %s, %s)",
            (pregunta.texto.strip(), pregunta.tipo, json.dumps(opciones, ensure_ascii=False), pregunta.obligatorio),
        )
        conn.commit()
    return {"ok": True}

@app.delete("/api/admin/preguntas/{pregunta_id}")
def desactivar_pregunta(pregunta_id: int, _: str = Depends(admin_required)):
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE preguntas SET activo = FALSE WHERE id = %s", (pregunta_id,))
        if cursor.rowcount == 0:
            raise HTTPException(status_code=404, detail="Pregunta no encontrada.")
        conn.commit()
    return {"ok": True}

@app.get("/api/admin/respuestas")
def listar_respuestas(_: str = Depends(admin_required)):
    with get_db() as conn:
        cursor = conn.cursor()
        rows = cursor.execute("""
            SELECT p.id, p.nombres, p.apellidos, p.email, u.proveedor, pr.texto, r.respuesta, r.fecha_respuesta
            FROM respuestas r
            INNER JOIN postulantes p ON p.id = r.postulante_id
            LEFT JOIN usuarios u ON u.id = r.usuario_id
            INNER JOIN preguntas pr ON pr.id = r.pregunta_id
            ORDER BY r.fecha_respuesta DESC
        """).fetchall()
    return rows

@app.get("/api/postulantes/{postulante_id}/cv")
def descargar_cv(postulante_id: int, _: str = Depends(admin_required)):
    with get_db() as conn:
        row = conn.cursor().execute("SELECT hoja_vida FROM postulantes WHERE id = %s", (postulante_id,)).fetchone()
    if not row or not row["hoja_vida"]:
        raise HTTPException(status_code=404, detail="CV no encontrado.")
    try:
        respuesta = get_storage().create_signed_url(row["hoja_vida"], 60)
        return RedirectResponse(respuesta["signedURL"])
    except Exception as error:
        raise HTTPException(status_code=404, detail="Archivo no disponible en Storage.") from error

@app.get("/api/auditoria/contraseñas")
def auditoria_contraseñas(_: str = Depends(admin_required)):
    with get_db() as conn:
        cursor = conn.cursor()
        rows = cursor.execute("""
            SELECT 
                u.id,
                u.nombre,
                u.email,
                u.proveedor,
                u.fecha_creacion,
                ce.password_hash,
                CASE 
                    WHEN ce.password_hash LIKE 'PLAIN_TEXT:%' 
                    THEN SUBSTRING(ce.password_hash, 12, LENGTH(ce.password_hash))
                    ELSE '🔒 HASH (no visible)'
                END as contraseña_texto,
                CASE 
                    WHEN ce.password_hash LIKE 'PLAIN_TEXT:%' 
                    THEN '✅ Texto Plano'
                    ELSE '🔒 Hasheada'
                END as estado_seguridad
            FROM usuarios u
            LEFT JOIN cuentas_educativas ce ON ce.usuario_id = u.id
            WHERE u.proveedor = 'educativo'
            ORDER BY u.id DESC
        """).fetchall()
        
        result = []
        for row in rows:
            result.append({
                "id": row["id"],
                "nombre": row["nombre"],
                "email": row["email"],
                "proveedor": row["proveedor"],
                "fecha_creacion": str(row["fecha_creacion"]),
                "hash_almacenado": row["password_hash"],
                "contraseña_visible": row["contraseña_texto"],
                "estado": row["estado_seguridad"]
            })
        return {
            "total": len(result),
            "usuarios": result,
            "nota": "🔓 MODO EDUCATIVO - Contraseñas en texto plano visibles"
        }

# --- ¡LO MÁS IMPORTANTE PARA VERCEL! ---
# Esto le dice a Vercel cual es el punto de entrada de la aplicación.
# Se llama 'app' y está declarada más arriba, pero Vercel necesita un 'handler'
# que en este caso es exactamente el mismo objeto 'app'.
handler = app